FROM golang:1.16-stretch

WORKDIR /go/src/github.com/uta8a/isucon-suburi-portal/

RUN apt-get update && apt-get install -y netcat

COPY go.mod go.mod
COPY go.sum go.sum

RUN go get -u github.com/cosmtrek/air

CMD [ "/go/src/github.com/uta8a/isucon-suburi-portal/local-dev/dev/run.sh" ]
